name: Build Docker Image

on:
  push:
  workflow_dispatch:

env:
    IS_DEFAULT_BRANCH: ${{ github.ref_name == github.event.repository.default_branch }}

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                submodules: recursive
                ref: ${{ github.ref }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images:
                  prowler1000/web-tools
                tags: |
                  type=raw,value=latest

            - name: Build image
              uses: docker/build-push-action@v5 
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-to: |
                  type=gha, mode=max, scope=${{github.ref_name}}
                cache-from: |
                  type=gha
                  type=gha, mode=max, scope=${{ github.ref_name }}

    
